/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


public class Principal extends javax.swing.JFrame {

    private int segundos;
    private int velocidadReloj;
    private int contadorDias;
    private static empresa empresa1;
    private static empresa empresa2;


    public Principal(int velocidadReloj,empresa empresa1, empresa empresa2) {
        this.velocidadReloj = 2 * velocidadReloj;
        this.empresa1=empresa1;
        this.empresa2=empresa2;
        
        segundos = 0;
        contadorDias = 0;
        initComponents();
        miInitComponents();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt("GANANCIAS EN BRUTO", 0, 0);
        model.setValueAt("COSTOS OPERATIVOS", 1, 0);
        model.setValueAt("UTILIDAD TOTAL", 2, 0);
    }

    private String formatoReloj(int segundos) {
        int horas = segundos / 3600;
        int minutos = (segundos % 3600) / 60;
        return String.format("%02d:%02d", horas, minutos);
    }

    private void miInitComponents() {
        reloj.setText("00:00");
        dia.setText("00");

        // Iniciamos un hilo en segundo plano para actualizar el reloj
        Thread relojThread = new Thread(new Runnable() {
            @Override
            public void run() {
                int segundosPorDia = 86400;
                while (true) {
                    try {
                        Thread.sleep(500); // Pausa de medio segundo
                        segundos += (segundosPorDia / velocidadReloj);
                        if (segundos >= segundosPorDia) {
                            segundos = 0; // Reiniciamos cuando se alcanza un día completo
                            contadorDias++; // Aumentamos un día
                            dia.setText(String.valueOf(contadorDias));
                        }
                        reloj.setText(formatoReloj(segundos));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });

        relojThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reloj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        empresa1_details = new javax.swing.JButton();
        empresa2_details = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        reloj.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        reloj.setText("00:00");

        jLabel1.setText("Hora:");

        jLabel2.setText("Día número:");

        dia.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dia.setText("00");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Parámetro", "Nintendo", "Capcom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(600);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        jButton1.setText("jButton1");

        empresa1_details.setText("Mostrar");
        empresa1_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa1_detailsActionPerformed(evt);
            }
        });

        empresa2_details.setText("Mostrar");
        empresa2_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa2_detailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reloj)
                            .addComponent(dia))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empresa1_details)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empresa2_details)))
                        .addGap(77, 77, 77))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reloj)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa1_details)
                    .addComponent(empresa2_details))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 81, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 82, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    private void empresa1_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa1_detailsActionPerformed
        // TODO add your handling code here:
        empresaInterfaz ventanaEmpresa1 = new empresaInterfaz(empresa1);
        ventanaEmpresa1.setVisible(true);  
        System.out.println("Empresa1 - Narrativa: " + empresa1.getDesarrolladoresNarrativa());
        System.out.println("Empresa2 - Narrativa: " + empresa2.getDesarrolladoresNarrativa());

        
    }//GEN-LAST:event_empresa1_detailsActionPerformed

    private void empresa2_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa2_detailsActionPerformed
        // TODO add your handling code here:
        empresaInterfaz ventanaEmpresa2 = new empresaInterfaz(empresa2);
        ventanaEmpresa2.setVisible(true);
        System.out.println("Empresa1 - Narrativa: " + empresa1.getDesarrolladoresNarrativa());
        System.out.println("Empresa2 - Narrativa: " + empresa2.getDesarrolladoresNarrativa());

    }//GEN-LAST:event_empresa2_detailsActionPerformed

    /**
     * @param args the command line arguments
     */

public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(10,empresa1,empresa2).setVisible(true); // Cambiado a 1000 para un segundo por tick
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dia;
    private javax.swing.JButton empresa1_details;
    private javax.swing.JButton empresa2_details;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel reloj;
    // End of variables declaration//GEN-END:variables
}
